var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/chat/route.js")
R.c("server/chunks/[root-of-the-server]__02mnj_n._.js")
R.c("server/chunks/_105f9b9._.js")
R.c("server/chunks/src_server_auth_jwt_ts_19m4omh._.js")
R.c("server/chunks/[root-of-the-server]__0xuaoik._.js")
R.c("server/chunks/[root-of-the-server]__1dbb677._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_1-pw2v2.js")
R.c("server/chunks/_next-internal_server_app_api_chat_route_actions_1d_pld-.js")
R.m(99280)
module.exports=R.m(99280).exports
