// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/login" | "/student" | "/student/knowledge" | "/student/practice" | "/student/simulator" | "/student/tests" | "/student/upload" | "/teacher" | "/teacher/resources" | "/teacher/students" | "/teacher/students/[id]"
type AppRouteHandlerRoutes = "/api/answers/submit" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/me" | "/api/auth/register" | "/api/chat" | "/api/curve-state" | "/api/curve-state/[id]" | "/api/knowledge" | "/api/questions/random" | "/api/questions/upload" | "/api/reports" | "/api/teacher/class-report" | "/api/teacher/class-report/pdf" | "/api/teacher/questions/approve" | "/api/teacher/questions/pending" | "/api/tests/start" | "/api/tests/submit"
type PageRoutes = never
type LayoutRoutes = "/" | "/student" | "/teacher"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/answers/submit": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/me": {}
  "/api/auth/register": {}
  "/api/chat": {}
  "/api/curve-state": {}
  "/api/curve-state/[id]": { "id": string; }
  "/api/knowledge": {}
  "/api/questions/random": {}
  "/api/questions/upload": {}
  "/api/reports": {}
  "/api/teacher/class-report": {}
  "/api/teacher/class-report/pdf": {}
  "/api/teacher/questions/approve": {}
  "/api/teacher/questions/pending": {}
  "/api/tests/start": {}
  "/api/tests/submit": {}
  "/login": {}
  "/student": {}
  "/student/knowledge": {}
  "/student/practice": {}
  "/student/simulator": {}
  "/student/tests": {}
  "/student/upload": {}
  "/teacher": {}
  "/teacher/resources": {}
  "/teacher/students": {}
  "/teacher/students/[id]": { "id": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/student": never
  "/teacher": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
