var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/register/route.js")
R.c("server/chunks/[root-of-the-server]__0iwgtrc._.js")
R.c("server/chunks/src_server_auth_jwt_ts_19m4omh._.js")
R.c("server/chunks/src_server_auth_password_ts_1vivag9._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_1-pw2v2.js")
R.c("server/chunks/_105f9b9._.js")
R.c("server/chunks/[root-of-the-server]__0xuaoik._.js")
R.c("server/chunks/_next-internal_server_app_api_auth_register_route_actions_0g4vfdr.js")
R.m(6706)
module.exports=R.m(6706).exports
