var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/answers/submit/route.js")
R.c("server/chunks/[root-of-the-server]__1nvilh4._.js")
R.c("server/chunks/_105f9b9._.js")
R.c("server/chunks/src_server_auth_jwt_ts_19m4omh._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_1-pw2v2.js")
R.c("server/chunks/[root-of-the-server]__1dbb677._.js")
R.c("server/chunks/[root-of-the-server]__0xuaoik._.js")
R.c("server/chunks/_next-internal_server_app_api_answers_submit_route_actions_1ssx0qb.js")
R.m(90081)
module.exports=R.m(90081).exports
