var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/teacher/students/[id]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1ldk622._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0k8i5pw.js")
R.c("server/chunks/ssr/_0w7b08m._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0gqiype._.js")
R.c("server/chunks/ssr/[root-of-the-server]__186sgu7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1map00z._.js")
R.c("server/chunks/ssr/src_app_layout_tsx_0r5yz5t._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_16h4pk_._.js")
R.c("server/chunks/ssr/_03augxp._.js")
R.c("server/chunks/ssr/_next-internal_server_app_teacher_students_[id]_page_actions_0t2q7ct.js")
R.m(21624)
module.exports=R.m(21624).exports
